builds:
- main: ./cmd/yamllint
  id: yamllint
  binary: yamllint
  env:
  - CGO_ENABLED=0
  targets:
  - linux_amd64
  - linux_arm64
release:
  mode: append
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true
