name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/go.sum"

      - name: run checks
        run: go run build check

      - name: build snapshot
        if: startsWith(matrix.os, 'ubuntu-')
        run: go run build snapshot
